// Generated by `pnpm --filter @quizez/api-client codegen` from ../../contracts/openapi.yaml
// Re-export typed client helpers here. Do NOT hand-write API types.
export type { paths } from "./schema";
